### ISSUE TITLE
招贤纳士 / Join us (･ω･)ﾉ

### ISSUE THREAD

**Issue by Dragon-Fish** [genshin-kit/genshin-kit-node#28]
**简体中文(zh-Hans)**

## 缘起

大家好，我是 `GenshinKit` 的原作者 @Dragon-Fish 

说到我为什么要开发这个库，要追溯到我很早之前为自己的聊天 bot —— [SILI酱](https://github.com/Wjghj-Project/Chatbot-SILI) —— 开发原神插件的时候，那个时候还没有什么 GenshinKit，只是一段硬编码在我 bot 里的一段“米游社查询”的工具函数。

在 bot 的插件发版以前，我突然想到，“米游社查询”这部分功能除了 bot 以外也许还有许多其他方面的用途，但是搜索了以后发现大多数人都是在做自己的实现，Python 方面倒是有人做单独的轮子，Node.js 这块完全是空缺的。

所以，我后来把“米游社查询”这部分功能解耦了，这也就是 GenshinKit 的来历。

## 现状

米游社/hoyolab 经常会更新 App 版本，而每一次版本更新都会修改其中的 **DS(动态密钥)算法**，这是米游社查询中至关重要的一环，如果这部分不跟进，那么查询功能很快就会被米哈游拦截而废掉。

### 国服

目前国服部分是由我（@Dragon-Fish ）跟进的。虽然我目前一直保持着跟进米游社的更新去更新 GenshinKit，**但是其最为核心的 DS 算法其实并不是我本人扒出来的，大多数时候只是参考其他的仓库然后改编为 JavaScript 版本**。

我深深感受到了自己技术力不足，逆向工程、反混淆这些我一概不会，更别说那些和数学有关的计算公式了，其实我本人是一名文科专业学生，对于数学方面的实际运用仅限于菜场砍价了（笑

另外，我本人目前在现实生活中是一名中国的大四学生，快毕业了，毕业以后我有很大概率是不会从事计算机相关工作的，是否有时间去摸代码实在是未知数。

### 国际服

目前国际服部分是由 @AlPha5130 (猫猫) 跟进的。国际服因为有 Web App 的缘故，获取 DS 算法相对来说容易一点。

但是从一堆打包混淆的代码里找到想要的部分依然不是什么容易的事情，而且猫猫目前也是一名大四学生，平时的空闲时间也不多，~~是被我硬拉来做苦力的~~，甚至被我拉来写 GenshinKit 的时候才被迫开始学习 TypeScript 的（笑

## 结语

能力不足加上缺少时间，指不定我们哪天就突然弃坑了，但这不是很可惜的一件事吗？所以现在很着急找到合作者一起维护这个库。

虽然我们目前——而且以后——一直会是开源库，参与进来不会获得任何物质上的收益，但是如果能交到有共同话题的朋友确实会是一件令人开心的事情。

**综上所述，如果您愿意，或者您知道谁可能有意愿一起维护这个库，请务必在此处留言或加入我们的 QQ 群 (･ω･)ﾉ**

> QQ 群：942425330

---

### 碎碎念

也许人数更多以后我们可以建一个QQ群或者 Discord 讨论组什么的，平时除了讨论技术以外还可以一起联机挖挖矿什么的（×

我们不仅从 GenshinKit 里拿不到一分钱收入，每个月出新卡还会给米哈游充好多钱。所以，假如您是米哈游员工——请放我们一马.jpg——我们的一切行为源于热爱，我保证我本人从来没有进行过任何很过分的缺德请求。

我永远喜欢《原神》(震声)！米哈游请多出点萝莉角色，别让我跪下来求你(震声)！

**Comment by ChanIok** [comment]
如何联系？虽然我很菜，逆向方面我也完全不懂（挠头，但在 TypeScript 上我大概能提供一点小帮助

**Comment by Dragon-Fish** [comment]
@ChanIok 如果能在 ts 方面提供帮助那真是帮大忙了，我已经把 QQ群号更新到一楼了，欢迎加入！

**Comment by Afanyiyu** [comment]
支持👍

**Comment by Dragon-Fish** [comment]
关闭 issue，只是为了好看，依然欢迎加入我们。

**Comment by wei-sys** [comment]
我想加入你们！
