### ISSUE TITLE
[BUG?] Request Failed 404

### ISSUE THREAD

**Issue by Sureiyaaa** [genshin-kit/genshin-kit-node#88]
**选择您要汇报的包/Choose the package you want to report.**

- [ ] @genshin-kit/core

I Just updated my Genshin-kit Core to 2.6.0 Previously I was using 2.5.0 (Genshin-Kit) and Tried to use the getUserInfo but I get a Request Failed 404 
Error: Request Failed with Status 404

![image](https://user-images.githubusercontent.com/46262050/145586270-58c9c574-fb4a-4c38-8170-4299f92739cf.png)

Environment
Node: 16.7.0

**Comment by Dragon-Fish** [comment]
see #87

seems like myy changed there api endpoint

**Comment by Sureiyaaa** [comment]
do I need to change something?

**Comment by Sureiyaaa** [comment]
Oh thanks it worked I changed it manually!
